In [1]:
from tools import tool
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#公司所属行业
com_industry_sql="""
    SELECT com_md5,com_industry FROM zhilian_company
"""
industry_data=pd.read_sql(com_industry_sql, tool.get_connnect())
industry_data.tail()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>com_md5</th>
      <th>com_industry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>80974</th>
      <td>fffe754783e0cdb5af279aedde59d9f5</td>
      <td>电子技术/半导体/集成电路</td>
    </tr>
    <tr>
      <th>80975</th>
      <td>fffef0b0260cc3e64fbb5a46e4fc0694</td>
      <td>快速消费品（食品/饮料/烟酒/日化）</td>
    </tr>
    <tr>
      <th>80976</th>
      <td>ffff349adef75ed6a9bffcc64059da16</td>
      <td>互联网/电子商务</td>
    </tr>
    <tr>
      <th>80977</th>
      <td>ffff5e817d44e50ce6f5ea632d66cbea</td>
      <td>家居/室内设计/装饰装潢</td>
    </tr>
    <tr>
      <th>80978</th>
      <td>ffffd8d811735b8d797a8eeffb816016</td>
      <td>基金/证券/期货/投资</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
#岗位薪资
job_salary_sql="""
	SELECT com_md5,salary_high,salary_low FROM zhilian_job
"""
salary_data=pd.read_sql(job_salary_sql,tool.get_connnect())
salary_data.tail()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>com_md5</th>
      <th>salary_high</th>
      <th>salary_low</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>438600</th>
      <td>6405145355eacbfbbd7d381a47ede1a2</td>
      <td>4000.0</td>
      <td>2001.0</td>
    </tr>
    <tr>
      <th>438601</th>
      <td>0006734f38be8e049b8395aa193efa97</td>
      <td>10000.0</td>
      <td>8001.0</td>
    </tr>
    <tr>
      <th>438602</th>
      <td>3a35bc859b964758ca9fb29d1e50a7cb</td>
      <td>10000.0</td>
      <td>8001.0</td>
    </tr>
    <tr>
      <th>438603</th>
      <td>5fcc27b43b072b38255111ad81cb74ff</td>
      <td>6000.0</td>
      <td>4001.0</td>
    </tr>
    <tr>
      <th>438604</th>
      <td>a4bdd07d83ec6a28d1108a213d3a19e8</td>
      <td>50000.0</td>
      <td>30001.0</td>
    </tr>
  </tbody>
</table>
</div>

In [18]:
#合并数据,各行业平均薪资
merge_res=pd.merge(industry_data,salary_data,on='com_md5')
grouped=merge_res.groupby(['com_industry'])
grouped.mean().sort_values(['salary_high'],ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>salary_high</th>
      <th>salary_low</th>
    </tr>
    <tr>
      <th>com_industry</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>基金/证券/期货/投资</th>
      <td>13426.511977</td>
      <td>8852.701858</td>
    </tr>
    <tr>
      <th>专业服务/咨询(财会/法律/人力资源等)</th>
      <td>10624.973856</td>
      <td>6960.645405</td>
    </tr>
    <tr>
      <th>网络游戏</th>
      <td>10584.143050</td>
      <td>6813.219973</td>
    </tr>
    <tr>
      <th>租赁服务</th>
      <td>10555.530903</td>
      <td>6868.600634</td>
    </tr>
    <tr>
      <th>信托/担保/拍卖/典当</th>
      <td>10495.812621</td>
      <td>7083.627173</td>
    </tr>
    <tr>
      <th>房地产/建筑/建材/工程</th>
      <td>10301.004606</td>
      <td>6900.027512</td>
    </tr>
    <tr>
      <th>银行</th>
      <td>9695.931901</td>
      <td>6603.542505</td>
    </tr>
    <tr>
      <th>跨领域经营</th>
      <td>9563.011396</td>
      <td>6366.849003</td>
    </tr>
    <tr>
      <th>中介服务</th>
      <td>9548.363914</td>
      <td>6561.010703</td>
    </tr>
    <tr>
      <th>能源/矿产/采掘/冶炼</th>
      <td>9365.471485</td>
      <td>6171.409373</td>
    </tr>
    <tr>
      <th>互联网/电子商务</th>
      <td>9317.717151</td>
      <td>6097.487872</td>
    </tr>
    <tr>
      <th>医药/生物工程</th>
      <td>9136.982916</td>
      <td>6072.687725</td>
    </tr>
    <tr>
      <th>环保</th>
      <td>9112.741043</td>
      <td>5907.168789</td>
    </tr>
    <tr>
      <th>农/林/牧/渔</th>
      <td>8985.585670</td>
      <td>5940.516545</td>
    </tr>
    <tr>
      <th>检验/检测/认证</th>
      <td>8652.530757</td>
      <td>5772.854110</td>
    </tr>
    <tr>
      <th>航空/航天研究与制造</th>
      <td>8618.170772</td>
      <td>5756.078818</td>
    </tr>
    <tr>
      <th>医疗/护理/美容/保健/卫生服务</th>
      <td>8602.571480</td>
      <td>5597.069857</td>
    </tr>
    <tr>
      <th>办公用品及设备</th>
      <td>8546.153846</td>
      <td>5527.056805</td>
    </tr>
    <tr>
      <th>计算机硬件</th>
      <td>8545.400636</td>
      <td>5412.308824</td>
    </tr>
    <tr>
      <th>保险</th>
      <td>8544.497087</td>
      <td>5754.331447</td>
    </tr>
    <tr>
      <th>通信/电信/网络设备</th>
      <td>8502.357339</td>
      <td>5462.115279</td>
    </tr>
    <tr>
      <th>交通/运输</th>
      <td>8496.692839</td>
      <td>5730.868852</td>
    </tr>
    <tr>
      <th>IT服务(系统/数据/维护)</th>
      <td>8490.040834</td>
      <td>5526.585544</td>
    </tr>
    <tr>
      <th>学术/科研</th>
      <td>8470.355149</td>
      <td>5412.732435</td>
    </tr>
    <tr>
      <th>石油/石化/化工</th>
      <td>8460.416235</td>
      <td>5530.382818</td>
    </tr>
    <tr>
      <th>政府/公共事业/非盈利机构</th>
      <td>8422.850829</td>
      <td>5506.277348</td>
    </tr>
    <tr>
      <th>其他</th>
      <td>8389.178499</td>
      <td>5285.000252</td>
    </tr>
    <tr>
      <th>家居/室内设计/装饰装潢</th>
      <td>8353.144404</td>
      <td>5575.457609</td>
    </tr>
    <tr>
      <th>电子技术/半导体/集成电路</th>
      <td>8302.687744</td>
      <td>5421.491073</td>
    </tr>
    <tr>
      <th>电气/电力/水利</th>
      <td>8286.107047</td>
      <td>5312.548951</td>
    </tr>
    <tr>
      <th>计算机软件</th>
      <td>8217.915824</td>
      <td>5332.106653</td>
    </tr>
    <tr>
      <th>仪器仪表及工业自动化</th>
      <td>8180.688428</td>
      <td>5293.724813</td>
    </tr>
    <tr>
      <th>通信/电信运营、增值服务</th>
      <td>8095.088227</td>
      <td>5256.190912</td>
    </tr>
    <tr>
      <th>医疗设备/器械</th>
      <td>8046.897709</td>
      <td>5236.006710</td>
    </tr>
    <tr>
      <th>汽车/摩托车</th>
      <td>8045.807884</td>
      <td>5230.825142</td>
    </tr>
    <tr>
      <th>耐用消费品（服饰/纺织/皮革/家具/家电）</th>
      <td>8002.329418</td>
      <td>5221.979217</td>
    </tr>
    <tr>
      <th>快速消费品（食品/饮料/烟酒/日化）</th>
      <td>7886.590373</td>
      <td>5210.781876</td>
    </tr>
    <tr>
      <th>媒体/出版/影视/文化传播</th>
      <td>7858.963848</td>
      <td>5163.344843</td>
    </tr>
    <tr>
      <th>旅游/度假</th>
      <td>7842.897927</td>
      <td>5131.728979</td>
    </tr>
    <tr>
      <th>加工制造（原料加工/模具）</th>
      <td>7797.128320</td>
      <td>5143.021622</td>
    </tr>
    <tr>
      <th>大型设备/机电设备/重工业</th>
      <td>7766.702323</td>
      <td>5025.429331</td>
    </tr>
    <tr>
      <th>物业管理/商业中心</th>
      <td>7722.124908</td>
      <td>5125.393129</td>
    </tr>
    <tr>
      <th>酒店/餐饮</th>
      <td>7679.743630</td>
      <td>5029.564014</td>
    </tr>
    <tr>
      <th>娱乐/体育/休闲</th>
      <td>7597.227926</td>
      <td>4965.425051</td>
    </tr>
    <tr>
      <th>教育/培训/院校</th>
      <td>7589.175917</td>
      <td>4920.719055</td>
    </tr>
    <tr>
      <th>广告/会展/公关</th>
      <td>7580.539738</td>
      <td>4934.585328</td>
    </tr>
    <tr>
      <th>外包服务</th>
      <td>7500.764968</td>
      <td>5017.475159</td>
    </tr>
    <tr>
      <th>印刷/包装/造纸</th>
      <td>7394.864155</td>
      <td>4790.444064</td>
    </tr>
    <tr>
      <th>礼品/玩具/工艺美术/收藏品/奢侈品</th>
      <td>7349.607143</td>
      <td>4855.278887</td>
    </tr>
    <tr>
      <th>贸易/进出口</th>
      <td>7313.252501</td>
      <td>4759.909384</td>
    </tr>
    <tr>
      <th>零售/批发</th>
      <td>6823.010373</td>
      <td>4387.593130</td>
    </tr>
    <tr>
      <th>物流/仓储</th>
      <td>6726.514896</td>
      <td>4531.675521</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
#可视化